---
app:
  name: invexcoin
  domain: invexcoin.com
  subdomain: staging
render_protect: false
csrfEnabled: false
ssl:
  enabled: true
  email: do-not-reply@invexcoin.com
images:
  peatio: quay.io/openware/peatio:2.4.19
  barong: quay.io/openware/barong:2.4.12
  frontend: quay.io/openware/baseapp:3.1.0-3f202ed # Check on quay.io/openware/baseapp for latest tags
  tower: quay.io/openware/tower:2.4.9
  rango: quay.io/openware/rango:2.4.3
finex:
  enabled: false
  image: quay.io/openware/finex:2.4.0-5334683
vendor:
  frontend: git@github.com:openware/baseapp.git
vault:
  token: s.Fy7JLoiatqjyHtPW3gzjXfgC
database:
  host: db
  port: 3306
  user: root
  password: changeme
storage:
  provider: AWS
  bucketName: documents
  region: sfo2
  endpoint: https://sfo2.digitaloceanspaces.com
  accessKey: "****"
  secretKey: "**********"
  signatureVersion: '2'
twilio:
  enabled: false
  phone_number: "+15005550000"
  account_sid: "changeme"
  auth_token: "changeme"
  content_template: "Your confirmation code is: {{code}}"
gaTrackerKey: ''
captcha:
  type: none
  siteKey: changeme
  secretKey: changeme
smtp:
  host: smtp.sendgrid.net
  port: 2525
  user: apikey
  password: changeme
  sender_email: noreply@postmaster.com
  sender_name: Postmaster
wallets:
  eth:
  - kind: deposit
    address: "changeme"
    max_balance: 0.0
    secret: changeme
  - kind: hot
    address: "changeme"
    max_balance: 100.0
    secret: changeme
  - kind: warm
    address: "changeme"
    max_balance: 1000.0
    secret: changeme
  - kind: fee
    address: "changeme"
    max_balance: 1000.0
    secret: changeme
  btc:
  - kind: deposit
    address: "changeme"
    max_balance: 0.0
  - kind: hot
    address: "changeme"
    max_balance: 100.0
  - kind: warm
    address: "changeme"
    max_balance: 1000.0
parity:
  network: mainnet
  address: parity
  rpcport: 8545
  port: 30303
bitcoind:
  enabled: true
  rpcuser: admin
  rpcpassword: changeme
  address: bitcoind
  network: mainnet
  rpcport: 8332
  port: 8333
litecoind:
  enabled: false
  rpcuser: admin
  rpcpassword: changeme
  address: litecoind
  network: testnet
  rpcport: 19332
  port: 19335
terraform:
  credentials: "~/safe/opendax.json"
  project: example-opendax
  region: europe-west4
  zone: europe-west4-a
  instance_name: opendax-cloud
  machine_type: n1-standard-4
  image: debian-cloud/debian-9
